package:
  name: fortytwo
  version: 1.0

source:
  path: ..

build:
  {% if BLD_TYPE=='noarch' %}
  noarch: python
  {% endif %}

  string: {{ BLD_WITH }}_{{ BLD_TYPE }}_{{ SCRIPT_WITH_PY }}
  entry_points:
    - fortytwo-ep = fortytwo.__init__:entry
  {% if BLD_WITH=='setup' %}
  script: python setup.py install
  {% else %}
  script: python -m pip install --no-deps --ignore-installed .
  {% endif %}

  {% if SCRIPT_WITH_PY=='py' %}
  script_env:
    - SCRIPT_WITH_PY
  {% endif %}


requirements:
  build:
    - python
